export type VariantType = "contained" | "outlined" | "text"
export type SizeType = "sm" | "md" | "lg"
export type ColorType =
    | "inherit"
    | "primary"
    | "secondary"
    | "success"
    | "error"
    | "info"
    | "warning"
export type ThemeType = "dark" | "light"
export type PositionType = "top" | "bottom" | "right" | "left"
